
services:
  web:
    build: .
    container_name: codestra_web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}
    env_file:
      - .env
    stdin_open: true
    tty: true
    networks:
      - codestra_network

  redis:
    image: "redis:alpine"
    container_name: codestra_redis
    networks:
      - codestra_network


  db:
    # image: postgis/postgis:13-3.1
    image: postgres:13
    container_name: codestra_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - codestra_network

  celery:
    build: .
    # command: celery --app=CORE worker -l INFO
    command: celery -A CORE.celery_app worker -l info
    volumes:
        - .:/app
    environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
        - ALLOWED_HOSTS=127.0.0.1,localhost,37.27.25.208

    depends_on:
        - web
        - redis
    networks:
      - codestra_network

  celery_beat:
    build: .
    command:
      [
        'celery',
        '--app=CORE',
        'beat',
        '--scheduler=django_celery_beat.schedulers:DatabaseScheduler',
        '--loglevel=INFO',
      ]
    volumes:
      - ./:/app
    depends_on:
      - web
      - db
      - redis
    networks:
      - codestra_network

  cache:
    image: redis:alpine
    container_name: rediss_cache
    restart: always

volumes:
  postgres_data:
  redis_data:

networks:
  codestra_network:
    driver: bridge

