# Generated by Django 5.1.4 on 2025-01-29 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descriptiion', models.TextField()),
                ('image', models.FileField(upload_to='cms/images')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('company_size', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('page', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('visiting_hours', models.CharField(blank=True, max_length=256, null=True)),
                ('representation_rnc', models.CharField(blank=True, max_length=256, null=True)),
                ('name_of_representative', models.CharField(blank=True, max_length=256, null=True)),
                ('representative_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('representative_cell_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('representative_email', models.CharField(blank=True, max_length=256, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='tax/image')),
                ('operation_carried_out_in_premise', models.CharField(blank=True, max_length=256, null=True)),
                ('street_of_warehouse', models.CharField(blank=True, max_length=256, null=True)),
                ('store_or_warehouse_number', models.CharField(blank=True, max_length=256, null=True)),
                ('province_of_warehouse', models.CharField(blank=True, max_length=256, null=True)),
                ('warehouse_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('local_administration', models.CharField(blank=True, max_length=256, null=True)),
                ('warehouse_sector', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_rnc', models.CharField(blank=True, max_length=256, null=True)),
                ('name_of_tax_payer', models.CharField(blank=True, max_length=256, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_telephone', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_cell_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_email', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_number', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_sector', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_province', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
