# Generated by Django 5.1.4 on 2025-01-19 20:59

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.CharField(default=cms.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False)),
                ('address_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('visiting_hours', models.CharField(blank=True, max_length=256, null=True)),
                ('representation_rnc', models.CharField(blank=True, max_length=256, null=True)),
                ('name_of_representative', models.CharField(blank=True, max_length=256, null=True)),
                ('representative_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('representative_cell_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('representative_email', models.CharField(blank=True, max_length=256, null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='tax/image')),
                ('operation_carried_out_in_premise', models.CharField(blank=True, max_length=256, null=True)),
                ('street_of_warehouse', models.CharField(blank=True, max_length=256, null=True)),
                ('store_or_warehouse_number', models.CharField(blank=True, max_length=256, null=True)),
                ('province_of_warehouse', models.CharField(blank=True, max_length=256, null=True)),
                ('warehouse_reference', models.CharField(blank=True, max_length=256, null=True)),
                ('local_administration', models.CharField(blank=True, max_length=256, null=True)),
                ('warehouse_sector', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_rnc', models.CharField(blank=True, max_length=256, null=True)),
                ('name_of_tax_payer', models.CharField(blank=True, max_length=256, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_telephone', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_cell_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_email', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_number', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_sector', models.CharField(blank=True, max_length=256, null=True)),
                ('tax_payer_province', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
