# Generated by Django 5.1.4 on 2025-01-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_taxpayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertitle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
