# Generated by Django 5.1.4 on 2025-01-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_headertitle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertitle',
            name='page',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
