# Generated by Django 5.1.4 on 2025-01-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_headertitle_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('rating', models.IntegerField()),
                ('message', models.TextField()),
                ('role', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name': 'Frequently Asked Question', 'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.AddField(
            model_name='headertitle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/images'),
        ),
        migrations.AddField(
            model_name='headertitle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cms/videos'),
        ),
    ]
