# Generated by Django 5.1.4 on 2025-01-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_testimonial_alter_faqs_options_headertitle_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
