# Generated by Django 5.1.4 on 2025-01-26 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_testimonial_image_alter_testimonial_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxpayer',
            name='media_file',
        ),
        migrations.CreateModel(
            name='TaxPayerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='tax/images')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='cms.taxpayer')),
            ],
        ),
    ]
