# Generated by Django 5.1.4 on 2025-01-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_career_careerapplication_question_option_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
