# Generated by Django 5.1.4 on 2025-01-20 23:34

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_first_name_alter_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=employee.models.generate_employee_id, max_length=256),
        ),
    ]
