# Generated by Django 5.1.4 on 2025-01-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='career',
        ),
        migrations.RemoveField(
            model_name='careerapplication',
            name='career',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='career',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='CareerApplication',
        ),
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
