# Generated by Django 5.1.4 on 2025-01-28 13:34

import career_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0002_option_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='id',
            field=models.CharField(default=career_app.models.generate_id, editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
