# Generated by Django 5.1.4 on 2025-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0003_alter_answer_id_alter_career_id_alter_option_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.EmailField(default='random user', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='full_name',
            field=models.CharField(default='random user', max_length=256),
            preserve_default=False,
        ),
    ]
