# Generated by Django 5.1.4 on 2025-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0004_remove_answer_user_answer_email_answer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
