# Generated by Django 5.1.4 on 2025-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='odoo_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
