# Generated by Django 5.1.4 on 2025-01-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_user_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='blog',
        ),
        migrations.AddField(
            model_name='visitor',
            name='page',
            field=models.URLField(default='http://localhost:8000'),
        ),
    ]
