# Generated by Django 5.1.4 on 2025-01-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_visitor_blog_visitor_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='method',
            field=models.CharField(blank=True, default='GET', max_length=10, null=True),
        ),
    ]
