# Generated by Django 5.1.4 on 2025-01-22 13:52

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_visitor_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.CharField(blank=True, default=auth_app.models.generate_client_id, max_length=256, null=True),
        ),
    ]
