# Generated by Django 5.1.4 on 2025-01-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        ('employee', '0002_remove_employee_address_employee_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
