# Generated by Django 5.1.4 on 2025-01-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_event_created_by'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('call', 'Call'), ('meeting', 'Meeting'), ('appointment', 'Appointment'), ('other', 'Other')], default='meeting', max_length=50),
        ),
    ]
