# Generated by Django 5.1.4 on 2025-01-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blogviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='can_publish_comment',
            field=models.BooleanField(default=False),
        ),
    ]
