# Generated by Django 5.1.4 on 2025-01-11 12:08

import blog_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment_can_publish_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogviewer',
            name='id',
            field=models.CharField(default=blog_app.models.generate_id, editable=False, max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default=blog_app.models.generate_id, editable=False, max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default=blog_app.models.generate_id, editable=False, max_length=70, primary_key=True, serialize=False),
        ),
    ]
